apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mesh-uat-go-two
  name: mesh-uat-go-two-envar-config
  namespace: klovercloud
data:
  RUN_MODE: PRODUCTION
  SERVER_PORT: "8080"
  MESH_UAT_GO_ONE_ENDPOINT: "http://mesh-uat-go-one.klovercloud.svc.cluster.local"
